### ISSUE TITLE
build instructions in Windows not working

### ISSUE THREAD

**Issue by carrotcypher** [canarytail/client#8]
**Problem**

Build instructions for Windows in the README call for setting environment variables:

```
C:\Users\tablet\Downloads\canarytail>$Env:GOOS="windows";
The filename, directory name, or volume label syntax is incorrect.

C:\Users\tablet\Downloads\canarytail>
```

This syntax is apparently not valid for Windows. 

I was able to build for Windows at least without any such variables set by just using `go build -o canarytail-windows-amd64.exe ./cmd/`.

**Comment by varbhat** [comment]
Did to try it in Powershell?

**Comment by carrotcypher** [comment]
Added in README that this assumes/requires Powershell, not Cmd terminal.
